# Generated by assistant to add is_short, external_url, thumbnail_url
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_comment_flagged_count_comment_is_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_short',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
